### ISSUE TITLE
sonata-project/cache abandoned but still required

### ISSUE THREAD

**Issue by Tobion** [sonata-project/SonataBlockBundle#1038]
https://github.com/sonata-project/cache is abandoned in packagist. But the SonataBlock bundle still requires it at the moment.
So it does not seem possible to get rid of the composer warning. Maybe remove the cache from the require section and make it optional?

**Comment by VincentLanglet** [comment]
Since the last version, all the cache-related are deprecated and you can disable them with one option
https://github.com/sonata-project/SonataBlockBundle/blob/4.x/UPGRADE-4.x.md#deprecated-caching-functionality

It will be drop in the 5.0 version. Until then, the warning is not a real issue IMHO
Making the package optional would require some extra-work for no real gain. But feel free to open a PR if you want to do it :)

**Comment by Tobion** [comment]
Yeah fine for me to wait until 5.0
