### ISSUE TITLE
Make soft/optional dependency for Templating component

### ISSUE THREAD

**Issue by Koc** [sonata-project/SonataBlockBundle#221]
Starting from Symfony 2.7 we can use twig directly without templating component. It could also improve performance a lot. But SonataBlockBundle has hard dependencies for this component and prevents disabling templating subsystem.

**Comment by Soullivaneuh** [comment]
Do you have some docs about it?

Also feel free to propose a PR.

**Comment by Koc** [comment]
http://symfony.com/blog/new-in-symfony-2-7-twig-as-a-first-class-citizen

https://github.com/symfony/symfony/issues/15028

**Comment by covex-nn** [comment]
@Soullivaneuh this issue is not outdated, even after 2 years.

> Well, for the templating part, the admin bundle should rather migrate to using the native Twig notation for templates, and using the Twig service directly. We precisely want to discourage the usage of the Templating wrapper in Flex projects.

(c) **stof** https://github.com/symfony/flex/issues/247#issuecomment-353320243

But to do this, second argument of `AbstractBlockService::__construct` must be changed from `EngineInterface $templating = null` to `\Twig\Environment $twig = null`. This is a lot of changes in all sonata-project bundles

* See https://github.com/sonata-project/SonataBlockBundle/blob/master/src/Block/Service/AbstractBlockService.php

**Comment by Koc** [comment]
ref #456
