### ISSUE TITLE
Autoregister blocks

### ISSUE THREAD

**Issue by core23** [sonata-project/SonataBlockBundle#471]
Today you have to register every newly created block under `sonata_block.blocks` (https://github.com/sonata-project/SonataBlockBundle/blob/3.x/src/DependencyInjection/Configuration.php#L127).

This is really annoying. So, what do you think about an autoregistration. Is there any case where you don't want to register a block that is tagged with `sonata.block`?

The same logic could be applied to breadcrumbs tagged with `sonata.breadcrumb`.

**Comment by greg0ire** [comment]
Can't imagine a case where you wouldn't want to register it, I think that would be a really great feature!

**Comment by core23** [comment]
The only case I could imagine is when you want to pass some custom options (context, templates, ...) to one specific block. But this can be done with a block override in the DI config.

**Comment by covex-nn** [comment]
I tried to autoregister blocks with `sonata_block.default_contexts` in [TweakCompilerPass::process](https://github.com/covex-nn/SonataBlockBundle/commit/3e6a4deb167647426abf86622898af5e169df558). But there was a error in Page Composer, because `sonata_page_bundle` contexts was added even to blocks not implemented `Sonata\BlockBundle\Block\Service\AdminBlockServiceInterface`.

I created PR to fix that error in Page Composer https://github.com/sonata-project/SonataPageBundle/pull/976
