### ISSUE TITLE
Remove Sonata Cache

### ISSUE THREAD

**Issue by core23** [sonata-project/SonataBlockBundle#663]
We should use symfony cache instead.

Even the doctrine cache was just deprecated in favor of symfony cache:
https://github.com/doctrine/DoctrineCacheBundle#deprecation-warning

**Comment by dmaicher** [comment]
So currently the only way to use caching in the `BlockBundle` is to rely on the abandoned `SonataCacheBundle`, or? As the caching related services are configured there.

Wondering if this cache functionality is actually something that is important to keep. Is anyone using this?

Maybe we can deprecate this whole caching completely instead of coming up with a PSR6 compatible cache support?

**Comment by VincentLanglet** [comment]
> Maybe we can deprecate this whole caching completely instead of coming up with a PSR6 compatible cache support?

That would be an easier solution indeed.

> Wondering if this cache functionality is actually something that is important to keep. Is anyone using this?

By default the Noop cache is used https://github.com/sonata-project/cache/blob/2.x/src/Adapter/Cache/NoopCache.php
I personnaly didn't change the value.

We currently have doc about it https://docs.sonata-project.org/projects/SonataBlockBundle/en/4.x/reference/cache/ so it's possible that someone are using it. But I'm not sure this feature is really needed @sonata-project/contributors

**Comment by core23** [comment]
> > Maybe we can deprecate this whole caching completely instead of coming up with a PSR6 compatible cache support?
> 
> That would be an easier solution indeed.

It should be okay for now. 👍 

If execution time is a problem, we can still add a better caching solution. The current implementation looks very complicated.

**Comment by VincentLanglet** [comment]
Do you want to take the deprecation/removal work @dmaicher ?

**Comment by dmaicher** [comment]
@VincentLanglet yes I will look into it. Shall we also consider this for the SonataPageBundle?

**Comment by VincentLanglet** [comment]
I don't know how is used the cache for SonataPageBundle. There is still more work to do on this bundle since we first need to add support for SonataAdminBundle v4 and SonataBlockBundle v4. 
In https://github.com/sonata-project/dev-kit/issues/1715, there is `Drop SonataCacheBundle` but I don't know if there was a strategy. If removing the cache on BlockBundle is going well, I'm not against doing the same for SonataPage.

If we succeed to deprecate the cache for BlockBundle, we might consider to release a new major to allow people to not download the sonata cache/cacheBundle anymore. Best would be to have a major version API compatible with the v4 to allow others bundle like SonataAdmin to support both v4 and v5.

**Comment by dmaicher** [comment]
@core23 @VincentLanglet so I started deprecating things and noticed that there is one more caching layer:

https://github.com/sonata-project/SonataBlockBundle/tree/4.x/src/Cache

Which is documented [here](https://docs.sonata-project.org/projects/SonataBlockBundle/en/4.x/reference/cache/#final-response-ttl-computation).

I would suggest to also deprecate this "Http caching layer" and `BlockInterface::getTtl()`. So basically everything caching related.

WDYT?

**Comment by VincentLanglet** [comment]
I agree
